### ISSUE TITLE
conferences: combine series and series_no in one

### ISSUE THREAD

**Issue by tomaszgy** [inspirehep/inspire-next#1461] opened 2016-08-18 09:33 UTC
Currently in the schema of conferences there're two different fields for conference series and conference series number:

      "series": {
            "title": "Conference series",
            "type": "array"
        },
      "series_number": {
            "title": "Conference series number",
            "type": "integer"
        },

I think it'd make more sense to have this information in the following form:

      "series": {
            "items": {
                "properties": {
                    "name": {
                        "title": "Series name",
                        "type": "string"
                    },
                    "number": {
                        "title": "Series number",
                        "type": "integer"
                    }
                },
                "type": "object"
            },
            "type": "array",
            "uniqueItems": true
        },

Also, that'd make my work with Neo4J easier :smile:

**Comment by jacquerie** [comment] 2016-08-18 09:35
Exact duplicate of https://github.com/inspirehep/inspire-next/issues/1228

**Closed by jacquerie** 2016-08-18 09:35 UTC

**Comment by tomaszgy** [comment] 2016-08-18 11:33
Sorry, I've forgotten about the previous one :smile:
