### ISSUE TITLE
Kb values used in current Inspire.

### ISSUE THREAD

**Issue by ioannistsanaktsidis** [inspirehep/inspire-next#941] opened 2016-02-29 14:12 UTC
After searching our current master branch, I detected the usages of the Kb values. So here is a small brief of the Kbs in  knwKB.json that we are actually using.
```
{
    "description": "Journals Abbreviations used by docextract",
    "id": 9,
    "is_api_accessible": true,
    "kbtype": "w",
    "name": "docextract-journals",
    "slug": "docextract-journals"
},
{
    "description": "Mapping of journal abbreviations to full names",
    "id": 2,
    "is_api_accessible": true,
    "kbtype": "w",
    "name": "JOURNALS",
    "slug": "journals"
},
{
    "description": "Coden to short title mappings",
    "id": 6,
    "is_api_accessible": true,
    "kbtype": "w",
    "name": "CODENS",
    "slug": "codens"
},
{
    "description": "Subjects KB (created for BibEdit)",
    "id": 8,
    "is_api_accessible": true,
    "kbtype": "w",
    "name": "Subjects",
    "slug": "subjects"
},
{
    "description": "List of type of Degrees",
    "id": 23,
    "is_api_accessible": true,
    "kbtype": "w",
    "name": "DEGREE",
    "slug": "degree"
},
```
We should check how to port this to invenio3 as invenio_knowledge will not be used anymore.

**Comment by ioannistsanaktsidis** [comment] 2016-02-29 14:13
cc @jmartinm  @kaplun  @jalavik

**Comment by ioannistsanaktsidis** [comment] 2016-02-29 15:14
The ones that can be converted to config variables are
```
"name": "DEGREE",
```
which contains 7 values,

```
"name": "Subjects",
```
which contains 14 values,

```
"name": "JOURNALS"
```
but there are 0 values,
and finally 
```
"name": "docextract-journals",
```
could also be a config variable, but there are really a lot of values(15.624).

**Comment by kaplun** [comment] 2016-02-29 20:59
@ioannistsanaktsidis I think this is duplicate of https://github.com/inspirehep/inspire-next/issues/927#issuecomment-189348469

Note that Journals should be based on the Journal records.

**Comment by kaplun** [comment] 2016-04-08 07:05
Moved into #927

**Closed by kaplun** 2016-04-08 07:05 UTC
