### ISSUE TITLE
HoldingPen: User submission in wrong dashboard box

### ISSUE THREAD

**Issue by ksachs** [inspirehep/inspire-next#3566] opened 2018-07-30 08:45 UTC
https://labs.inspirehep.net/api/holdingpen/1149133

## Current Behavior
is listed in [Publisher Updates - ERROR](https://labs.inspirehep.net/holdingpen/list/?data_type=hep&is-update=true&q=-metadata.acquisition_source.source:arXiv%20AND%20metadata.acquisition_source.method:hepcrawl&size=10&status=ERROR)

## Expected Behavior
I think it is a 'New Literature Submissions'

## Metadata

    "acquisition_source": {
      "datetime": "2018-07-30T03:35:57.506752", 
      "email": "horvathy@univ-tours.fr", 
      "method": "hepcrawl", 
      "orcid": "0000-0002-6337-4494", 
      "submission_number": "1149133"
    }, 
    "arxiv_eprints": [
      {
        "categories": [
          "quant-ph", 
          "cond-mat.quant-gas"
        ], 
        "value": "1805.00144"
      }
    ], 
    "publication_info": [
      {
        "artid": "013846", 
        "journal_title": "Phys.Rev.A", 
        "journal_volume": "98", 
        "material": "publication", 
        "pubinfo_freetext": "Phys. Rev. A 98, 013846 (2018)", 
        "year": 2018
      }
    ],

**Comment by StellaCh** [comment] 2018-08-13 12:59
Looks like it's an update: _**Submission**: Harvested on 2018-07-30T03:35:57.506752 from using hepcrawl_
Where did you find the user submission?

**Comment by ksachs** [comment] 2018-08-13 13:06
I thought only user submissions have `"acquisition_source":` with a person.

**Comment by michamos** [comment] 2018-08-13 13:08
the merger currently updates `acquisition_source`, but because `orcid` and `email` are not there for `hepcrawl`, when the record getting updated was a submission, we get strange `acquisition_source`s combining information from both.

**Comment by StellaCh** [comment] 2018-08-14 09:13
not a bug in dashboard box then, closing the ticket

**Closed** 2018-08-14 09:38 UTC
