### ISSUE TITLE
holding pen: no link to final record

### ISSUE THREAD

**Issue by annetteholtkamp** [inspirehep/inspire-next#2128] opened 2017-03-24 08:46 UTC
When a submission has been completely processed, no link to the final record appears in the holding pen. Just the message "accepted as core/noncore" is visble.

**Comment by jmartinm** [comment] 2017-03-27 13:03
Duplicate of https://github.com/inspirehep/inspire-next/issues/2024

**Closed by jmartinm** 2017-03-27 13:03 UTC
