### ISSUE TITLE
holdingpen ui: the 'can't save until state changes' button does not fit the container

### ISSUE THREAD

**Issue by david-caro** [inspirehep/inspire-next#2085] opened 2017-03-21 19:16 UTC
See attached screenshot, with firefox

![screenshot from 2017-03-21 20-14-48](https://cloud.githubusercontent.com/assets/587148/24166364/464b40d2-0e73-11e7-805a-61a9a30fc782.png)

**Comment by jmartinm** [comment] 2017-03-24 08:32
duplicate of https://github.com/inspirehep/inspire-next/issues/1967

**Closed by jmartinm** 2017-03-24 08:32 UTC
