### ISSUE TITLE
HoldingPen: Workflow: number of CORE references

### ISSUE THREAD

**Issue by ksachs** [inspirehep/inspire-next#3473] opened 2018-06-18 12:45 UTC
same as #2644

**Comment by ksachs** [comment] 2018-06-19 10:46
Algorithm at DESY:
C: number of references to CORE papers
T: total number of resolvable references
    
- propose as CORE if
C/T > 0.4 and T > 4
- otherwise propose as Accept if
C/T > 0.4 
C/T > 0.1 and C > 3
C > 10

@michamos You can play with the numbers but unless a machine-learning approach is significantly better than such a simple algorithm I would prefer the simple approach which can be tuned easily.

**Comment by michamos** [comment] 2018-06-19 11:35
The new machine learning algorithm is not ready for production yet. Before putting it in production, I'll make sure to compare with your simple decision strategy to make sure it performs significantly better. 

In its current iteration, it's doing something similar to this, but looking at the core/total and non-core/total ratios, and learning optimal cuts based on data, rather than setting them by hand. Because they are simple cuts, they are still very easy to interpret though.

**Comment by ksachs** [comment] 2018-06-19 11:44
are you sure you have the best set of parameters? C/T + N/T =1 so they are highly correlated. I would guess you need one absolute number, either C or T as parameter.

**Comment by michamos** [comment] 2018-06-19 12:07
As you can see in the slides I shared, it's really 2D, because for the total it's taking the total number of references (linked or unlinked). As @annetteholtkamp suggested, we might try changing that to number of potentially resolved references (i.e. references with arXiv ID, or DOI, or complete pubnote, etc.).

**Comment by ksachs** [comment] 2018-06-19 14:16
I forgot the resolvable but rejected references. So T = C + N + R. Still you need an absolute number in the parameter set. Don't work with ratios only.

**Comment by fschwenn** [comment] 2018-06-22 08:30
Keep also in mind that we changed the policy for astro. At the moment, a high N for an astro-paper means less than a high N for a nucl-paper.

**Comment by fschwenn** [comment] 2018-07-04 10:58
I also would recommend to use the number of potentially resolved references (that's also what we do at the moment at DESY). Otherwise a 0/40 can either mean "nothing interesting cited" or "refextract failed completely". E. g. today
https://labs.inspirehep.net/holdingpen/1111565
 0/42 core, 7/42 matched
But when I run refextract on legacy it finds 22 of the references in INSPIRE.

**Comment by michamos** [comment] 2018-07-04 13:04
that's where both numbers are displayed: (# core references)/(# references), and (# linked references)/(# references). I think the real question here is how you get 22 references whereas the workflow only gets 7. Could you send me the list of cited records to compare?

**Comment by ksachs** [comment] 2018-07-04 13:08
It might be a similar effect as mentioned in https://github.com/inspirehep/inspire-next/issues/3529.
There might be a significant number of references that are resolved only on legacy.

@fschwenn 's point is to exclude references that are not easily resolvable from the analysis. I think you had that on your to-do list anyhow.

**Comment by michamos** [comment] 2018-07-04 13:12
@ksachs sorry, but I don't see how this has anything to do with the issue you mention which concerns the merger.

We have run the reference matcher on all references in INSPIRE, and have determined that there are no big differences except for metadata issues in references. That's why I think it would be very interesting to have a closer look at the huge difference in this case.

> @fschwenn 's point is to exclude references that are not easily resolvable from the analysis. I think you had that on your to-do list anyhow.

Yes, that would be a nice improvement for the future.

**Comment by ksachs** [comment] 2018-07-05 07:58
@michamos correct. But that record is a nice example.

in https://labs.inspirehep.net/holdingpen/list/?page=1&size=10&q=1807.00620
you see that the original has significantly less resolved references than the update which includes legacy information.

I created a condensed list of the references for the [original](http://www-library.desy.de/tmp/metadata_ref_original.txt) and the [update](http://www-library.desy.de/tmp/metadata_ref_update.txt).

So you can see that e.g. `"raw_refs.value": "[5] S. Weinberg, Phys. Rev. Lett. 40 (1978) 223."`
is not resolved in https://labs.inspirehep.net/api/holdingpen/1108662

**Comment by michamos** [comment] 2018-07-06 11:58
@ksachs The missing references were caused by a subtle bug related to ES sharding, which is fixed in #3534.

**Comment by Dinika** [comment] 2018-07-06 12:16
Fixed in [PR 85](https://github.com/inspirehep/inspirehep-search-js/pull/85)

**Comment by Dinika** [comment] 2018-07-06 12:16
Fixed in [PR 85](https://github.com/inspirehep/inspirehep-search-js/pull/85)

**Closed by Dinika** 2018-07-06 12:16 UTC
Labels: Priority: high
