### ISSUE TITLE
Error in submitting paper

### ISSUE THREAD

**Issue by annetteholtkamp** [inspirehep/inspire-next#2400] opened 2017-06-01 15:23 UTC
## Current Behavior
If I click Submit it says "Saved, but with errors"
The POST request indeed receives as JSON response:
```json
{"messages":{"abstract":{},"additional_url":{},"arxiv_id":{},"authors":{"messages":["Got unexpected value type","Got unexpected value type","Got unexpected value type","Got unexpected value type","Got unexpected value type","Got unexpected value type","Got unexpected value type"],"state":"error"},"categories_arXiv":{},"collaboration":{},"conf_name":{},"conference_id":{},"defense_date":{},"degree_type":{},"doi":{},"experiment":{},"extra_comments":{},"institution":{},"issue":{},"journal_title":{},"language":{},"license_url":{},"note":{},"other_language":{},"page_range_article_id":{},"preprint_created":{},"references":{},"report_numbers":{},"subject":{},"supervisors":{},"thesis_date":{},"title":{},"title_arXiv":{},"title_crossref":{},"title_translation":{},"type_of_doc":{},"url":{},"volume":{},"year":{}}}
```

## Steps to Reproduce (for bugs)

1. Submit new record
2. Enter 10.1063/1.4953647 and import
3. complete the affiliations with CERN & Keio U.
4. Click on submit

**Comment by annetteholtkamp** [comment] 2017-06-01 15:24
cc: @jmartinm, @david-caro, @jacquerie

**Comment by jacquerie** [comment] 2017-06-01 15:36
The bad news is that I tested this live in production, but the good news is that it went through: https://labs.inspirehep.net/holdingpen/649833

BTW I added the `Theory-Nucl` category, but I'm not really sure it's correct...

**Comment by david-caro** [comment] 2017-06-01 15:47
Might it be related to this error from the web nodes? It's related to the references.
```python
2017-06-01 13:45:54,805 ERROR: TransportError(400, u'action_request_validation_exception', u'Validation Failed: 1: no documents to g│··········································································································
et;') [in /opt/inspire/src/inspire/inspirehep/modules/search/api.py:95]                                                             │··········································································································
Traceback (most recent call last):                                                                                                  │··········································································································
  File "/opt/inspire/src/inspire/inspirehep/modules/search/api.py", line 91, in mget                                                │··········································································································
    **kwargs                                                                                                                        │··········································································································
  File "/opt/inspire/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped                               │··········································································································
    return func(*args, params=params, **kwargs)                                                                                     │··········································································································
  File "/opt/inspire/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 408, in mget                               │··········································································································
    doc_type, '_mget'), params=params, body=body)                                                                                   │··········································································································
  File "/opt/inspire/lib/python2.7/site-packages/elasticsearch/transport.py", line 327, in perform_request                          │··········································································································
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)                   │··········································································································
  File "/opt/inspire/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 84, in perform_request            │··········································································································
    self._raise_error(response.status_code, raw_data)                                                                               │··········································································································
  File "/opt/inspire/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 114, in _raise_error                       │··········································································································
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)                             │··········································································································
RequestError: TransportError(400, u'action_request_validation_exception', u'Validation Failed: 1: no documents to get;')    ```

**Comment by jacquerie** [comment] 2017-06-01 16:48
I doubt it... that exception stacktrace is generated here: https://github.com/inspirehep/inspire-next/blob/f2e42539c409f9ece36338bb5df03ba47437d7a1/inspirehep/modules/search/api.py#L95

Note that it is actually preventing the exception, printing the stacktrace and returning an empty list.

**Comment by jacquerie** [comment] 2017-06-02 08:02
> BTW I added the Theory-Nucl category, but I'm not really sure it's correct...

In fact, before adding a category I was getting the same error... could it be that this was the problem, @annetteholtkamp ?

**Comment by jmartinm** [comment] 2017-06-26 07:53
Closing since cannot be reproduced

**Closed by jmartinm** 2017-06-26 07:53 UTC
Labels: project/submission, Type: Bug
