### ISSUE TITLE
OR query giving wrong results

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#2829] opened 2017-10-02 12:55 UTC
Performing the following query: `control_number:1497201 OR control_number:1498589` generates:

```json
{
    "query": {
        "bool": {
            "filter": [
                {
                    "bool": {
                        "must_not": [
                            {
                                "match": {
                                    "_collections": "HERMES Internal Notes"
                                }
                            }
                        ],
                        "must": [
                            {
                                "match": {
                                    "_collections": "literature"
                                }
                            }
                        ]
                    }
                }
            ],
            "should": [
                {
                    "match": {
                        "control_number": "1497201"
                    }
                },
                {
                    "match": {
                        "control_number": "1498589"
                    }
                }
            ]
        }
    },
    "from": 0,
    "size": 25
}
```

which is returning all results (instead of the expected 2).

I think the problem is due to the use of `should` together with `filter` https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html#query-dsl-bool-query

> The clause (query) should appear in the matching document. If the bool query is in a query context and has a must or filter clause then a document will match the bool query even if none of the should queries match.

**Comment by jmartinm** [comment] 2017-10-02 12:56
Actually just realised that the issue is already there - https://github.com/inspirehep/inspire-next/issues/1792

**Comment by jmartinm** [comment] 2017-10-02 12:57
@chris-asl Is this something you can have a look at?

**Comment by jacquerie** [comment] 2017-10-03 05:56
While it's true that OR queries are broken, the query that it's trying to do here is the product of insufficient API design: instead of implementing an endpoint that takes a POST with a list of recids, we are trying to generate this weird-looking query.

**Comment by chris-asl** [comment] 2017-10-04 11:42
According to [this](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html) 

> The clause (query) should appear in the matching document. If the bool query is in a [query context](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-filter-context.html) and has a `must` or `filter` clause then a document will match the bool query even if none of the `should` queries match. In this case these clauses are only used to influence the score. If the `bool` query is a [filter context](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-filter-context.html) or has neither `must` or `filter` then at least one of the `should` queries must match a document for it to match the bool query. This behavior may be explicitly controlled by settings the [minimum_should_match](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-minimum-should-match.html) parameter.

So, we currently have a `bool` query in a `query` context, which has a `filter` clause and we're falling into the case of **a document will match the bool query even if none of the `should` queries match**.
This means, that when an ElasticSearch query object is created with a filter, we should be adding the `"minimum_should_match": 1`, as @jmartinm suggested also [here](https://github.com/inspirehep/inspire-next/issues/1792#issuecomment-265442894).

I will create a PR on [`invenio-search`](https://github.com/inveniosoftware/invenio-search).

**Comment by chris-asl** [comment] 2017-10-19 09:20
The issue is resolved since https://github.com/inveniosoftware/invenio-search/pull/105 has been merged to upstream. Currently `title holography or bosons` returns three results, as it should.

**Closed by chris-asl** 2017-10-19 09:20 UTC
Labels: Type: Bug
