### ISSUE TITLE
Introduce format cache

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#478] opened 2015-11-09 10:02 UTC
We should introduce introduce support for caching brief/detailed formats via Redis. A simple API you should allow the invalidation of the format (e.g. when a record receives a new citation).

**Comment by jmartinm** [comment] 2016-02-03 14:33
Duplicate of https://github.com/inspirehep/inspire-next/issues/515

**Closed by jmartinm** 2016-02-03 14:33 UTC
Labels: enhancement
