### ISSUE TITLE
Holding Pen: bulk-decision ignores check-box

### ISSUE THREAD

**Issue by ksachs** [inspirehep/inspire-next#2579] opened 2017-07-31 09:27 UTC
## Expected Behavior

bulk-decision (clicking the top 'Article Decisions') should act on records selected by the check-boxes, not on all in the current filter.

## Current Behavior

The counter in the 'NN article workflows with decisions to be made' is correct, corresponding to the number of checked records. But the action is performed on all filtered records.

## Steps to Reproduce (for bugs)

1. open holdingpen listing (e.g. with 9 records)
2. check several records, not all (e.g. 7 records)
A box for 'Article Decisions' appears with the number of checked articles. 
3. click one action, it will act on all 9 records not just the selected 7.

## Screenshots (if appropriate):
![hp_bulk-decision_1](https://user-images.githubusercontent.com/7591594/28771421-071a15b4-75e3-11e7-9d18-6ec7fc907ed3.png)
![hp_bulk-decision_2](https://user-images.githubusercontent.com/7591594/28771420-0714c866-75e3-11e7-9b8f-8de2b535a543.png)

**Comment by jacquerie** [comment] 2017-08-01 16:47
In local testing I'm finding that this is a display bug, not a more serious one: it's true that all records switch to "Waiting", but only those records whose checkbox was selected have the action performed on them. I will make a video to show what I'm seeing.

**Comment by jacquerie** [comment] 2017-08-01 19:18
Ignore my previous comment: this is the serious bug.

**Comment by jmartinm** [comment] 2017-08-01 19:37
> Ignore my previous comment: this is the serious bug.

I can fix this tomorrow.

**Comment by jacquerie** [comment] 2017-08-01 19:51
...in fact, it looks like the ordering of the records and the checkboxes presented to the user do not match, so selecting a subset of a selection via checkboxes results in applying the bulk operation to essentially a random subset of the records. That's really bad!

**Comment by jmartinm** [comment] 2017-08-02 06:59
I have not yet been able to reproduce this locally. Tried with 4 different records in the HoldingPen selecting 2 of them and doing batch actions Core and Accept and only the selected ones got affected.

**Comment by ksachs** [comment] 2017-08-02 07:05
I think it happens only when you first select all (the checkbox next to Details) and then de-select some records.

**Comment by ksachs** [comment] 2017-08-02 07:12
![screenshot from 2017-08-02 09 06 56](https://user-images.githubusercontent.com/7591594/28861767-9f1a9976-7762-11e7-9a16-bc2e1660e75c.png)
![screenshot from 2017-08-02 09 07 57](https://user-images.githubusercontent.com/7591594/28861768-9f1af290-7762-11e7-8039-50c9c164f1bb.png)
![screenshot from 2017-08-02 09 08 58](https://user-images.githubusercontent.com/7591594/28861769-9f1c464a-7762-11e7-86dd-7a15d5311454.png)
![screenshot from 2017-08-02 09 09 25](https://user-images.githubusercontent.com/7591594/28861770-9f1fb848-7762-11e7-9213-cd8d0cec8b3d.png)

**Comment by jmartinm** [comment] 2017-08-02 07:13
Thanks, will try that now.

**Comment by jmartinm** [comment] 2017-08-02 08:16
Found the culprit, will be fixed in https://github.com/inspirehep/inspirehep-search-js/pull/37

**Closed** 2017-08-02 08:48 UTC
Labels: Type: Bug
