### ISSUE TITLE
Port formatter functionality

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#929] opened 2016-02-26 10:13 UTC
```bash
formatter/
├── __init__.py
├── config.py
├── output_formats
│   ├── __init__.py
│   ├── hb.yml
│   ├── hbinst.yml
│   ├── hca.yml
│   ├── hcv.yml
│   ├── hd.yml
│   ├── hdact.yml
│   ├── hdfile.yml
│   ├── he.yml
│   ├── hlxe.yml
│   ├── hlxh.yml
│   ├── hlxu.yml
│   ├── hp.yml
│   ├── hra.yml
│   ├── hrf.yml
│   ├── hrn.yml
│   ├── hru.yml
│   ├── htcv.yml
│   ├── hx.yml
│   ├── tlcv.yml
│   ├── xd.yml
│   ├── xm.yml
│   ├── xn.yml
│   └── xsti.yml
└── views.py
```

Use the `RECORDS_REST_ENDPOINTS` [configuration](https://github.com/inspirehep/inspire-next/blob/invenio3/inspirehep/config.py#L83).

There, one can define for each export type a serializer:

```
RECORDS_REST_ENDPOINTS = dict(
    literature=dict(
        pid_type='literature',
        pid_minter='inspire_recid_minter',
        pid_fetcher='inspire_recid_fetcher',
        search_index='records-hep',
        search_type='hep',
        record_serializers={
            'application/json': ('invenio_records_rest.serializers'
                                 ':json_v1_response'),
            'application/marcxml+xml': (
                'inspirehep.modules.records.serializers.marcxml_v1_response'),
            'application/x-cv+text': (
                'inspirehep.modules.records.serializers.cv_text_v1_response'),
            'application/x-bibtex': (
                'inspirehep.modules.records.serializers.bibtex_v1_response'),

        },
        search_serializers={
            'application/json': ('invenio_records_rest.serializers'
                                 ':json_v1_search'),
            'application/vnd+inspire.brief+json': ('inspirehep.modules.records.serializers'
                                                   ':json_brief_v1_search'),
        },
        list_route='/literature/',
        item_route='/literature/<pid_value>',
        default_media_type='application/json',
        max_result_window=10000,
        query_factory_imp='inspirehep.modules.search.query:inspire_query_factory',
    ),
```

The logic of the exports (bibtex and so on) can be reused.

Then from the UI we will call the REST Api to retrieve them.

Previous ongoing porting is here https://github.com/inspirehep/inspire-next/pull/903

**Comment by kaplun** [comment] 2016-02-26 15:43
cc @jacenkow for what we discussed right now IRL

**Comment by ioannistsanaktsidis** [comment] 2016-04-20 09:22
@kaplun @jmartinm as we merged the formats we can close this issue.

**Comment by kaplun** [comment] 2016-04-20 10:14
Great :) It will be closed automatically by the merge action

**Comment by jacquerie** [comment] 2016-04-20 11:28
Err... the commit message didn't mention this issue. So this has to be closed manually, I think.

**Closed by jacquerie** 2016-04-20 11:28 UTC

**Comment by ioannistsanaktsidis** [comment] 2016-04-20 11:38
👍  Exactly @jacquerie thnx!

**Comment by kaplun** [comment] 2016-04-20 11:43
But: https://github.com/ioannistsanaktsidis/inspire-next/commit/cdb8958d219b46b37df2defcb7f1261ad25334c3

wasn't it saying: `Closes #929.` ?

Is this not respected by github?

**Comment by jacquerie** [comment] 2016-04-20 11:48
Ah, right, I was only looking at the PR message. Uhm, maybe the problem is the dot after the issue number?

**Comment by ioannistsanaktsidis** [comment] 2016-04-20 11:59
@kaplun hmmmm I guess the problem is the dot as @jacquerie  mentions. Whatever, in the end it should remain close :P Cheers 💃
