### ISSUE TITLE
editor: allows you to put anything in the language field

### ISSUE THREAD

**Issue by david-caro** [inspirehep/inspire-next#2090] opened 2017-03-21 19:40 UTC
![screenshot from 2017-03-21 20-39-36](https://cloud.githubusercontent.com/assets/587148/24167295/9019ce74-0e76-11e7-8422-496ddc6f8474.png)

**Comment by jmartinm** [comment] 2017-03-24 08:39
Seems duplicate of https://github.com/inspirehep/record-editor/issues/121

**Closed by jmartinm** 2017-03-24 08:39 UTC
