### ISSUE TITLE
wrong files get attached to holding pen records

### ISSUE THREAD

**Issue by michamos** [inspirehep/inspire-next#2238] opened 2017-04-19 15:03 UTC
https://labs.inspirehep.net/holdingpen/619315 has an attached PDF, which is the PDF from a different record, namely https://labs.inspirehep.net/holdingpen/619303. Looks like the problem is on our side, as the submitters are different, and there is no PDF in the `formdata`.

**Comment by jacquerie** [comment] 2017-04-19 22:04
That's interesting. I actually see different PDFs in the two records. I definitely remember seeing two equal PDFs on your screen, so what's going on? Maybe wrong caching from the Angular application?

**Comment by michamos** [comment] 2017-04-20 09:11
Maybe it was fixed by @annetteholtkamp ?

**Comment by jmartinm** [comment] 2017-05-01 10:27
Just managed to reproduce this locally. Will dig deeper to see what is the cause.

**Comment by jmartinm** [comment] 2017-05-01 13:12
Problem seems to be in the workflows Python code btw, in the [submit view](https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/literaturesuggest/views.py#L84) every time we create the Workflow object, it is reusing the previous extra_data. To reproduce:

```python
In [1]: from invenio_db import db

In [2]: from invenio_workflows import workflow_object_class

In [3]: workflow_object = workflow_object_class.create(
   ...:         data={},
   ...:         id_user=1,
   ...:         data_type="hep"
   ...:     )

In [4]: workflow_object.extra_data['foo'] = 'bar'

In [5]: workflow_object.save()
--------------------------------------------------------------------------------
DEBUG in api [/Users/jmartinm/.virtualenvs/inspirehep/src/invenio-workflows/invenio_workflows/api.py:133]:
Saved object: 3 at []
--------------------------------------------------------------------------------

In [6]: db.session.commit()

In [7]: workflow_object
Out[7]: <WorkflowObject(id = 3, id_workflow = None, status = ObjectStatus.INITIAL, id_parent = None, created = 2017-05-01 15:06:50.728624, )

In [9]: workflow_object.extra_data
Out[9]: {u'foo': u'bar'}

In [10]: workflow_object = workflow_object_class.create(
    ...:         data={},
    ...:         id_user=1,
    ...:         data_type="hep"
    ...:     )

In [11]: workflow_object.extra_data
Out[11]: {'foo': 'bar'}
```

**Comment by jmartinm** [comment] 2017-05-03 07:38
Fixed in https://github.com/inveniosoftware-contrib/invenio-workflows/pull/40

**Closed by jmartinm** 2017-05-03 07:38 UTC
Labels: project/workflows, Status: WIP, Type: Bug
